[package]
name = "remote64-client"
version = "0.1.0"
edition = "2021"

[dependencies]
remote64-common = { path = "../common" }

log = "0.4"
env_logger = "0.9"
clap = { version = "3.1", features = ["cargo", "env"] }

minifb = "0.22"
cpal = "0.13"
crossbeam-queue = "0.3"