[package]
name = "remote64-common"
version = "0.1.0"
edition = "2021"

[dependencies]
num_enum = "0.5"
num-traits = "0.2"
zstd = "*"

log = "0.4"
env_logger = "0.9"
strum = "0.24"
strum_macros = "0.24"